# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\flippr.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Flippr(object):
    def setupUi(self, Flippr):
        Flippr.setObjectName("Flippr")
        Flippr.resize(629, 174)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Flippr.sizePolicy().hasHeightForWidth())
        Flippr.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(Flippr)
        self.centralwidget.setObjectName("centralwidget")
        self.controls_box = QtWidgets.QGroupBox(self.centralwidget)
        self.controls_box.setGeometry(QtCore.QRect(10, 10, 201, 161))
        self.controls_box.setObjectName("controls_box")
        self.layoutWidget = QtWidgets.QWidget(self.controls_box)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 20, 181, 131))
        self.layoutWidget.setObjectName("layoutWidget")
        self.controls_layout = QtWidgets.QGridLayout(self.layoutWidget)
        self.controls_layout.setContentsMargins(0, 0, 0, 0)
        self.controls_layout.setObjectName("controls_layout")
        self.comp_spin = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.comp_spin.setSuffix("")
        self.comp_spin.setDecimals(3)
        self.comp_spin.setMinimum(0.001)
        self.comp_spin.setProperty("value", 0.1)
        self.comp_spin.setObjectName("comp_spin")
        self.controls_layout.addWidget(self.comp_spin, 3, 1, 1, 1)
        self.decay_spin = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.decay_spin.setDecimals(6)
        self.decay_spin.setMinimum(0.0)
        self.decay_spin.setProperty("value", 0.25)
        self.decay_spin.setObjectName("decay_spin")
        self.controls_layout.addWidget(self.decay_spin, 2, 1, 1, 1)
        self.comp_label = QtWidgets.QLabel(self.layoutWidget)
        self.comp_label.setObjectName("comp_label")
        self.controls_layout.addWidget(self.comp_label, 3, 0, 1, 1)
        self.on_button = QtWidgets.QPushButton(self.layoutWidget)
        self.on_button.setObjectName("on_button")
        self.controls_layout.addWidget(self.on_button, 5, 0, 1, 2)
        self.running_indicator = QtWidgets.QLineEdit(self.layoutWidget)
        self.running_indicator.setEnabled(False)
        self.running_indicator.setText("")
        self.running_indicator.setObjectName("running_indicator")
        self.controls_layout.addWidget(self.running_indicator, 6, 0, 1, 2)
        self.decay_label = QtWidgets.QLabel(self.layoutWidget)
        self.decay_label.setObjectName("decay_label")
        self.controls_layout.addWidget(self.decay_label, 2, 0, 1, 1)
        self.amplitude_label = QtWidgets.QLabel(self.layoutWidget)
        self.amplitude_label.setObjectName("amplitude_label")
        self.controls_layout.addWidget(self.amplitude_label, 0, 0, 2, 1)
        self.amplitude_spin = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.amplitude_spin.setSuffix("")
        self.amplitude_spin.setDecimals(3)
        self.amplitude_spin.setMinimum(0.001)
        self.amplitude_spin.setProperty("value", 0.1)
        self.amplitude_spin.setObjectName("amplitude_spin")
        self.controls_layout.addWidget(self.amplitude_spin, 0, 1, 2, 1)
        self.diagnostics_box = QtWidgets.QGroupBox(self.centralwidget)
        self.diagnostics_box.setGeometry(QtCore.QRect(220, 10, 180, 161))
        self.diagnostics_box.setObjectName("diagnostics_box")
        self.gridLayoutWidget = QtWidgets.QWidget(self.diagnostics_box)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 20, 160, 131))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.diagnostics_layout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.diagnostics_layout.setContentsMargins(0, 0, 0, 0)
        self.diagnostics_layout.setObjectName("diagnostics_layout")
        self.frequency_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.frequency_label.setObjectName("frequency_label")
        self.diagnostics_layout.addWidget(self.frequency_label, 0, 0, 1, 1)
        self.freq_lineedit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.freq_lineedit.setEnabled(False)
        self.freq_lineedit.setClearButtonEnabled(False)
        self.freq_lineedit.setObjectName("freq_lineedit")
        self.diagnostics_layout.addWidget(self.freq_lineedit, 0, 1, 1, 1)
        self.missed_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.missed_label.setObjectName("missed_label")
        self.diagnostics_layout.addWidget(self.missed_label, 1, 0, 1, 1)
        self.missed_lineedit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.missed_lineedit.setEnabled(False)
        self.missed_lineedit.setObjectName("missed_lineedit")
        self.diagnostics_layout.addWidget(self.missed_lineedit, 1, 1, 1, 1)
        self.pulseOutput = QtWidgets.QWidget(self.centralwidget)
        self.pulseOutput.setGeometry(QtCore.QRect(410, 10, 211, 161))
        self.pulseOutput.setObjectName("pulseOutput")
        Flippr.setCentralWidget(self.centralwidget)
        self.comp_label.setBuddy(self.amplitude_spin)
        self.decay_label.setBuddy(self.decay_spin)
        self.amplitude_label.setBuddy(self.amplitude_spin)

        self.retranslateUi(Flippr)
        QtCore.QMetaObject.connectSlotsByName(Flippr)
        Flippr.setTabOrder(self.amplitude_spin, self.decay_spin)
        Flippr.setTabOrder(self.decay_spin, self.on_button)
        Flippr.setTabOrder(self.on_button, self.running_indicator)
        Flippr.setTabOrder(self.running_indicator, self.freq_lineedit)
        Flippr.setTabOrder(self.freq_lineedit, self.missed_lineedit)

    def retranslateUi(self, Flippr):
        _translate = QtCore.QCoreApplication.translate
        Flippr.setWindowTitle(_translate("Flippr", "Flippr"))
        self.controls_box.setTitle(_translate("Flippr", "Controls"))
        self.comp_label.setText(_translate("Flippr", "Compensation"))
        self.on_button.setText(_translate("Flippr", "ON/OFF"))
        self.decay_label.setText(_translate("Flippr", "Constant"))
        self.amplitude_label.setText(_translate("Flippr", "Amplitude"))
        self.diagnostics_box.setTitle(_translate("Flippr", "Diagnostics"))
        self.frequency_label.setText(_translate("Flippr", "Frequency"))
        self.missed_label.setText(_translate("Flippr", "Missed"))

